function get_mapdata() {
  return [
    {
      "address": "康普巷45号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 29,
      "imgUrl": "",
      "name": "阿杜客栈",
      "score": 10,
      "latitude": 26.91744,
      "longtitude": 100.20839
    },
    {
      "address": "新义街密士巷40号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 30,
      "imgUrl": "",
      "name": "阿溢灿阁",
      "score": 10,
      "latitude": 26.87342,
      "longtitude": 100.23481
    },
    {
      "address": "光义街光碧巷62号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 31,
      "imgUrl": "",
      "name": "爱花园",
      "score": 10,
      "latitude": 26.86886,
      "longtitude": 100.23278
    },
    {
      "address": "新华街翠文段53号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 32,
      "imgUrl": "",
      "name": "爱上丽江客栈",
      "score": 10,
      "latitude": 26.87294,
      "longtitude": 100.23329
    },
    {
      "address": "新华街翠文段88号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 33,
      "imgUrl": "",
      "name": "安心客栈",
      "score": 10,
      "latitude": 26.87375,
      "longtitude": 100.23329
    },
    {
      "address": "文明村文林巷150-2",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 34,
      "imgUrl": "",
      "name": "桉胤阁客栈",
      "score": 10,
      "latitude": 26.87455,
      "longtitude": 100.24521
    },
    {
      "address": "锦天国际北院",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 35,
      "imgUrl": "",
      "name": "半城记忆客栈",
      "score": 10,
      "latitude": 26.86873,
      "longtitude": 100.22793
    },
    {
      "address": "文生巷53号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 36,
      "imgUrl": "",
      "name": "半朵幽莲",
      "score": 10,
      "latitude": 26.87434,
      "longtitude": 100.24299
    },
    {
      "address": "不远行馆",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 37,
      "imgUrl": "",
      "name": "不远客栈",
      "score": 10,
      "latitude": 26.87284,
      "longtitude": 100.23657
    },
    {
      "address": "束河古城鹿苑路龙泉路交界东康6组",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 38,
      "imgUrl": "",
      "name": "茶马斗斤客栈",
      "score": 10,
      "latitude": 26.92065,
      "longtitude": 100.20733
    },
    {
      "address": "东康7组20号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 39,
      "imgUrl": "",
      "name": "禅茶一心客栈",
      "score": 10,
      "latitude": 26.92065,
      "longtitude": 100.20733
    },
    {
      "address": "幸福小区",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 40,
      "imgUrl": "",
      "name": "车友汇别墅酒店",
      "score": 10,
      "latitude": 26.86,
      "longtitude": 100.25398
    },
    {
      "address": "东康村7组59号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 41,
      "imgUrl": "",
      "name": "初见水木家园客栈",
      "score": 10,
      "latitude": 26.91835,
      "longtitude": 100.20882
    },
    {
      "address": "七一街官门口84号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 42,
      "imgUrl": "",
      "name": "初一客栈",
      "score": 10,
      "latitude": 26.87017,
      "longtitude": 100.23657
    },
    {
      "address": "光义街新院巷20号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 43,
      "imgUrl": "",
      "name": "翠微兰房",
      "score": 10,
      "latitude": 26.87389,
      "longtitude": 100.23287
    },
    {
      "address": "五一街王家庄巷23号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 44,
      "imgUrl": "",
      "name": "大花猫客栈",
      "score": 10,
      "latitude": 26.87029,
      "longtitude": 100.23891
    },
    {
      "address": "古城区子云巷21号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 45,
      "imgUrl": "",
      "name": "大水车思语客栈",
      "score": 10,
      "latitude": 26.878,
      "longtitude": 100.23817
    },
    {
      "address": "束河仁里路29号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 46,
      "imgUrl": "",
      "name": "灯火阑珊客栈",
      "score": 10,
      "latitude": 26.9206,
      "longtitude": 100.20148
    },
    {
      "address": "茶马驿站F7-1（A1、A2）",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 47,
      "imgUrl": "",
      "name": "等你客栈",
      "score": 10,
      "latitude": 26.91745,
      "longtitude": 100.20552
    },
    {
      "address": "五一街王家庄巷84号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 48,
      "imgUrl": "",
      "name": "鼎源客栈",
      "score": 10,
      "latitude": 26.87103,
      "longtitude": 100.23885
    },
    {
      "address": "七一街八一上段88号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 49,
      "imgUrl": "",
      "name": "东东外客栈",
      "score": 10,
      "latitude": 26.86936,
      "longtitude": 100.23778
    },
    {
      "address": "古城区北门街玉河商场111号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 50,
      "imgUrl": "",
      "name": "朵儿客栈",
      "score": 10,
      "latitude": 26.87784,
      "longtitude": 100.23668
    },
    {
      "address": "石屏上村178号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 51,
      "imgUrl": "",
      "name": "飞行的厨房（云栖店）",
      "score": 10,
      "latitude": 26.8641,
      "longtitude": 100.24985
    },
    {
      "address": "新华街黄山上段40号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 52,
      "imgUrl": "",
      "name": "丰泽居客栈",
      "score": 10,
      "latitude": 26.87195,
      "longtitude": 100.23095
    },
    {
      "address": "康仲村22号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 53,
      "imgUrl": "",
      "name": "浮生部落",
      "score": 10,
      "latitude": 26.85771,
      "longtitude": 100.22483
    },
    {
      "address": "文生巷174-9号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 54,
      "imgUrl": "",
      "name": "盖家别院",
      "score": 10,
      "latitude": 26.87399,
      "longtitude": 100.24105
    },
    {
      "address": "束河松云村1组39号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 55,
      "imgUrl": "",
      "name": "高海拔客栈",
      "score": 10,
      "latitude": 26.91951,
      "longtitude": 100.20152
    },
    {
      "address": "七一街兴文巷63号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 56,
      "imgUrl": "",
      "name": "古城画院客栈",
      "score": 10,
      "latitude": 26.86893,
      "longtitude": 100.23554
    },
    {
      "address": "光义街新苑巷20号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 57,
      "imgUrl": "",
      "name": "古城阳光客栈",
      "score": 10,
      "latitude": 26.87105,
      "longtitude": 100.23488
    },
    {
      "address": "金甲路345号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 58,
      "imgUrl": "",
      "name": "古道云端客栈",
      "score": 10,
      "latitude": 26.87095,
      "longtitude": 100.22652
    },
    {
      "address": "五一街兴仁下段30号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 59,
      "imgUrl": "",
      "name": "古月坊客栈",
      "score": 10,
      "latitude": 26.87379,
      "longtitude": 100.23566
    },
    {
      "address": "新华街黄山上段59号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 60,
      "imgUrl": "",
      "name": "古云客栈",
      "score": 10,
      "latitude": 26.87122,
      "longtitude": 100.23221
    },
    {
      "address": "义尚街文林巷28号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 61,
      "imgUrl": "",
      "name": "海阔天空客栈",
      "score": 10,
      "latitude": 26.87485,
      "longtitude": 100.24435
    },
    {
      "address": "东康村6组19号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 62,
      "imgUrl": "",
      "name": "好玩斋客栈",
      "score": 10,
      "latitude": 26.91736,
      "longtitude": 100.20654
    },
    {
      "address": "五一街王家庄巷42号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 63,
      "imgUrl": "",
      "name": "红尘净土客栈",
      "score": 10,
      "latitude": 26.87088,
      "longtitude": 100.23954
    },
    {
      "address": "五一街文治巷127号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 64,
      "imgUrl": "",
      "name": "红尘与醉",
      "score": 10,
      "latitude": 26.87306,
      "longtitude": 100.23837
    },
    {
      "address": "金星街174号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 65,
      "imgUrl": "",
      "name": "鸿意古客栈",
      "score": 10,
      "latitude": 26.87265,
      "longtitude": 100.22824
    },
    {
      "address": "光义街昭庆巷19-2号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 66,
      "imgUrl": "",
      "name": "花好月圆客栈（木府二院）",
      "score": 10,
      "latitude": 26.86749,
      "longtitude": 100.23637
    },
    {
      "address": "束河松云村一组17号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 67,
      "imgUrl": "",
      "name": "花楼之恋",
      "score": 10,
      "latitude": 26.92032,
      "longtitude": 100.20086
    },
    {
      "address": "束河古镇松云村18号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 68,
      "imgUrl": "",
      "name": "花水木客栈",
      "score": 10,
      "latitude": 26.91909,
      "longtitude": 100.20048
    },
    {
      "address": "街尾巷89号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 69,
      "imgUrl": "",
      "name": "花溪锦巷客栈",
      "score": 10,
      "latitude": 26.92048,
      "longtitude": 100.20453
    },
    {
      "address": "光义街光碧巷66",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 70,
      "imgUrl": "",
      "name": "花筑栖溪客栈",
      "score": 10,
      "latitude": 26.86869,
      "longtitude": 100.23247
    },
    {
      "address": "季宝屋东段14号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 71,
      "imgUrl": "",
      "name": "江河骑迹观景客栈",
      "score": 10,
      "latitude": 26.8651,
      "longtitude": 100.24475
    },
    {
      "address": "束河松云村1组45号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 72,
      "imgUrl": "",
      "name": "结漫客栈",
      "score": 10,
      "latitude": 26.91805,
      "longtitude": 100.19926
    },
    {
      "address": "束河松云村3组13号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 73,
      "imgUrl": "",
      "name": "解语花舍客栈",
      "score": 10,
      "latitude": 26.91886,
      "longtitude": 100.20085
    },
    {
      "address": "束河北门中和路63号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 74,
      "imgUrl": "",
      "name": "金逸园客栈",
      "score": 10,
      "latitude": 26.92164,
      "longtitude": 100.20484
    },
    {
      "address": "云南省丽江市古城区丽江古城景区老磨坊精品酒店",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 75,
      "imgUrl": "",
      "name": "墨青客栈",
      "score": 10,
      "latitude": 26.92164,
      "longtitude": 100.20484
    },
    {
      "address": "龙泉路81",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 76,
      "imgUrl": "",
      "name": "静园客栈",
      "score": 10,
      "latitude": 26.92175,
      "longtitude": 100.2059
    },
    {
      "address": "七一街八一下段50号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 77,
      "imgUrl": "",
      "name": "镜花别苑客栈",
      "score": 10,
      "latitude": 26.86944,
      "longtitude": 100.24126
    },
    {
      "address": "光义街光义巷7号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 78,
      "imgUrl": "",
      "name": "镜花园客栈",
      "score": 10,
      "latitude": 26.87005,
      "longtitude": 100.23486
    },
    {
      "address": "云南省丽江市古城区祥和办事处义和社区白龙潭村21号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 79,
      "imgUrl": "",
      "name": "九洲客栈",
      "score": 10,
      "latitude": 26.86463,
      "longtitude": 100.2308
    },
    {
      "address": "五一街兴仁下段26-5",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 80,
      "imgUrl": "",
      "name": "来嘛客栈",
      "score": 10,
      "latitude": 26.87309,
      "longtitude": 100.23535
    },
    {
      "address": "祥和路泊龙水榭二期",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 81,
      "imgUrl": "",
      "name": "来如意酒店",
      "score": 10,
      "latitude": 26.86191,
      "longtitude": 100.22962
    },
    {
      "address": "五一街文生巷97-1（念你客栈对面）",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 82,
      "imgUrl": "",
      "name": "赖着不走客栈",
      "score": 10,
      "latitude": 26.87302,
      "longtitude": 100.24064
    },
    {
      "address": "昭庆村31号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 83,
      "imgUrl": "",
      "name": "蓝莎心苑",
      "score": 10,
      "latitude": 26.86858,
      "longtitude": 100.2367
    },
    {
      "address": "中和村王家巷31号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 84,
      "imgUrl": "",
      "name": "懒窝窝客栈",
      "score": 10,
      "latitude": 26.9227,
      "longtitude": 100.20572
    },
    {
      "address": "五一街文明巷",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 85,
      "imgUrl": "",
      "name": "朗豪客栈",
      "score": 10,
      "latitude": 26.87549,
      "longtitude": 100.24468
    },
    {
      "address": "文林巷40号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 86,
      "imgUrl": "",
      "name": "老班长青旅",
      "score": 10,
      "latitude": 26.87536,
      "longtitude": 100.24471
    },
    {
      "address": "东康八组",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 87,
      "imgUrl": "",
      "name": "老夫子客栈",
      "score": 10,
      "latitude": 26.91876,
      "longtitude": 100.20794
    },
    {
      "address": "王家庄巷70-2号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 88,
      "imgUrl": "",
      "name": "老叶和九十九个老板娘",
      "score": 10,
      "latitude": 26.87144,
      "longtitude": 100.23862
    },
    {
      "address": "文明村13号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 89,
      "imgUrl": "",
      "name": "李家院客栈",
      "score": 10,
      "latitude": 26.87306,
      "longtitude": 100.24053
    },
    {
      "address": "丽江官房别墅619栋",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 90,
      "imgUrl": "",
      "name": "丽江官房别墅619栋",
      "score": 10,
      "latitude": 26.90817,
      "longtitude": 100.21911
    },
    {
      "address": "丽江官房别墅632栋",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 91,
      "imgUrl": "",
      "name": "丽江官房别墅632栋",
      "score": 10,
      "latitude": 26.90817,
      "longtitude": 100.21911
    },
    {
      "address": "丽江官房别墅678栋",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 92,
      "imgUrl": "",
      "name": "丽江官房别墅678栋",
      "score": 10,
      "latitude": 26.90817,
      "longtitude": 100.21911
    },
    {
      "address": "中和路79号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 93,
      "imgUrl": "",
      "name": "丽江吉相观景精品客栈",
      "score": 10,
      "latitude": 26.92297,
      "longtitude": 100.20671
    },
    {
      "address": "玉河走廊玉缘路（工商银行旁）",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 94,
      "imgUrl": "",
      "name": "丽江梦成客栈",
      "score": 10,
      "latitude": 26.87789,
      "longtitude": 100.2343
    },
    {
      "address": "丽景湾18号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 95,
      "imgUrl": "",
      "name": "丽景湾别墅酒店",
      "score": 10,
      "latitude": 26.8604,
      "longtitude": 100.23398
    },
    {
      "address": "义尚街文明巷45号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 96,
      "imgUrl": "",
      "name": "丽垸居客栈",
      "score": 10,
      "latitude": 26.87364,
      "longtitude": 100.24242
    },
    {
      "address": "文明巷128号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 97,
      "imgUrl": "",
      "name": "莲境客栈（江南水乡）",
      "score": 10,
      "latitude": 26.87278,
      "longtitude": 100.24455
    },
    {
      "address": "束河松云村松园路36号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 98,
      "imgUrl": "",
      "name": "龙凤别院客栈",
      "score": 10,
      "latitude": 26.91771,
      "longtitude": 100.19968
    },
    {
      "address": "金甲路536号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 99,
      "imgUrl": "",
      "name": "旅之屋青年旅社",
      "score": 10,
      "latitude": 26.87108,
      "longtitude": 100.22803
    },
    {
      "address": "义尚社区文明村98附号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 100,
      "imgUrl": "",
      "name": "芒果客栈",
      "score": 10,
      "latitude": 26.86853,
      "longtitude": 100.24689
    },
    {
      "address": "茶马驿站C7-1栋",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 101,
      "imgUrl": "",
      "name": "美好夏天客栈",
      "score": 10,
      "latitude": 26.91731,
      "longtitude": 100.20456
    },
    {
      "address": "兴文巷73号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 102,
      "imgUrl": "",
      "name": "梦秋客栈",
      "score": 10,
      "latitude": 26.86984,
      "longtitude": 100.2357
    },
    {
      "address": "文明巷154号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 103,
      "imgUrl": "",
      "name": "梦田别院客栈",
      "score": 10,
      "latitude": 26.8729,
      "longtitude": 100.24489
    },
    {
      "address": "中和路王家巷28号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 104,
      "imgUrl": "",
      "name": "墨里客栈",
      "score": 10,
      "latitude": 26.92236,
      "longtitude": 100.20538
    },
    {
      "address": "",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 105,
      "imgUrl": "",
      "name": "墨青客栈",
      "score": 10,
      "latitude": 26.87106,
      "longtitude": 100.23618
    },
    {
      "address": "五一街兴仁中段47-2号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 106,
      "imgUrl": "",
      "name": "木过柯客栈",
      "score": 10,
      "latitude": 26.87223,
      "longtitude": 100.23662
    },
    {
      "address": "昭庆村5号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 107,
      "imgUrl": "",
      "name": "木心居客栈",
      "score": 10,
      "latitude": 26.86823,
      "longtitude": 100.23745
    },
    {
      "address": "街尾巷60号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 108,
      "imgUrl": "",
      "name": "木鱼客栈",
      "score": 10,
      "latitude": 26.92054,
      "longtitude": 100.2049
    },
    {
      "address": "黄山上段19号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 109,
      "imgUrl": "",
      "name": "沐兰别苑",
      "score": 10,
      "latitude": 26.87287,
      "longtitude": 100.23184
    },
    {
      "address": "五一街兴仁上段26号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 110,
      "imgUrl": "",
      "name": "沐云听风客栈",
      "score": 10,
      "latitude": 26.8729,
      "longtitude": 100.23749
    },
    {
      "address": "文生巷77号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 111,
      "imgUrl": "",
      "name": "慕名而来二店",
      "score": 10,
      "latitude": 26.87343,
      "longtitude": 100.24266
    },
    {
      "address": "民主路与福慧路交叉口东南",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 112,
      "imgUrl": "",
      "name": "纳美居",
      "score": 10,
      "latitude": 26.8734,
      "longtitude": 100.24423
    },
    {
      "address": "束河街道东康村6组",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 113,
      "imgUrl": "",
      "name": "栖语客栈",
      "score": 10,
      "latitude": 26.91808,
      "longtitude": 100.20725
    },
    {
      "address": "束河古镇东康7组21号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 114,
      "imgUrl": "",
      "name": "千幕轩客栈",
      "score": 10,
      "latitude": 26.92081,
      "longtitude": 100.20899
    },
    {
      "address": "新华街黄山上段36号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 115,
      "imgUrl": "",
      "name": "蔷薇序",
      "score": 10,
      "latitude": 26.87191,
      "longtitude": 100.23122
    },
    {
      "address": "老街尾巷55号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 116,
      "imgUrl": "",
      "name": "且停居客栈",
      "score": 10,
      "latitude": 26.92178,
      "longtitude": 100.20509
    },
    {
      "address": "文庙巷91号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 117,
      "imgUrl": "",
      "name": "秦时明月（香汀店）",
      "score": 10,
      "latitude": 26.87542,
      "longtitude": 100.24281
    },
    {
      "address": "街尾村29号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 118,
      "imgUrl": "",
      "name": "青楼客栈",
      "score": 10,
      "latitude": 26.92089,
      "longtitude": 100.20506
    },
    {
      "address": "七星街下段31号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 119,
      "imgUrl": "",
      "name": "清玖青年旅舍",
      "score": 10,
      "latitude": 26.87374,
      "longtitude": 100.22747
    },
    {
      "address": "云南省丽江市古城区义尚街文明巷96",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 120,
      "imgUrl": "",
      "name": "清雅轩客栈",
      "score": 10,
      "latitude": 26.87314,
      "longtitude": 100.24446
    },
    {
      "address": "五一街文生巷109号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 121,
      "imgUrl": "",
      "name": "仁和花影客栈",
      "score": 10,
      "latitude": 26.87302,
      "longtitude": 100.24021
    },
    {
      "address": "兴仁中段28号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 122,
      "imgUrl": "",
      "name": "如归轩",
      "score": 10,
      "latitude": 26.87306,
      "longtitude": 100.23658
    },
    {
      "address": "束河东康村7组65号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 123,
      "imgUrl": "",
      "name": "瑞景纳客栈",
      "score": 10,
      "latitude": 26.91785,
      "longtitude": 100.20942
    },
    {
      "address": "万子桥附近",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 124,
      "imgUrl": "",
      "name": "三间房",
      "score": 10,
      "latitude": 26.87038,
      "longtitude": 100.23725
    },
    {
      "address": "北门街玉河商场巷110号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 125,
      "imgUrl": "",
      "name": "三毛家客栈（一店）",
      "score": 10,
      "latitude": 26.87736,
      "longtitude": 100.2365
    },
    {
      "address": "新华街双石段59号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 126,
      "imgUrl": "",
      "name": "山居 醉花荫观景客栈",
      "score": 10,
      "latitude": 26.87522,
      "longtitude": 100.23308
    },
    {
      "address": "黄山上段73号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 127,
      "imgUrl": "",
      "name": "狮山花客",
      "score": 10,
      "latitude": 26.8715,
      "longtitude": 100.22962
    },
    {
      "address": "五一街兴仁中段53号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 128,
      "imgUrl": "",
      "name": "十九花居客栈",
      "score": 10,
      "latitude": 26.87212,
      "longtitude": 100.23637
    },
    {
      "address": "义尚街文明巷62号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 129,
      "imgUrl": "",
      "name": "时光静好客栈",
      "score": 10,
      "latitude": 26.87407,
      "longtitude": 100.24241
    },
    {
      "address": "光义街新院巷",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 130,
      "imgUrl": "",
      "name": "似水年华客栈",
      "score": 10,
      "latitude": 26.87084,
      "longtitude": 100.23435
    },
    {
      "address": "义尚街文明巷54号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 131,
      "imgUrl": "",
      "name": "水墨印象客栈",
      "score": 10,
      "latitude": 26.87364,
      "longtitude": 100.24241
    },
    {
      "address": "五一街兴仁上段11号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 132,
      "imgUrl": "",
      "name": "水上之风",
      "score": 10,
      "latitude": 26.87361,
      "longtitude": 100.2368
    },
    {
      "address": "四方听音广场旁边F8-1号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 133,
      "imgUrl": "",
      "name": "水榭花厅客栈",
      "score": 10,
      "latitude": 26.91763,
      "longtitude": 100.20528
    },
    {
      "address": "新华街黄山上段38号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 134,
      "imgUrl": "",
      "name": "水月庄客栈",
      "score": 10,
      "latitude": 26.87193,
      "longtitude": 100.23104
    },
    {
      "address": "七一街八一下段15号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 135,
      "imgUrl": "",
      "name": "水悦客栈",
      "score": 10,
      "latitude": 26.86947,
      "longtitude": 100.23949
    },
    {
      "address": "七一街八一下段188号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 136,
      "imgUrl": "",
      "name": "四月物语",
      "score": 10,
      "latitude": 26.86824,
      "longtitude": 100.24062
    },
    {
      "address": "五一街文治巷87号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 137,
      "imgUrl": "",
      "name": "他乡故事涵舍",
      "score": 10,
      "latitude": 26.87261,
      "longtitude": 100.23948
    },
    {
      "address": "大民航路太和园",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 138,
      "imgUrl": "",
      "name": "太和文化园",
      "score": 10,
      "latitude": 26.856875,
      "longtitude": 100.259125
    },
    {
      "address": "束河放水冲街四方听音广场旁",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 139,
      "imgUrl": "",
      "name": "糖小主客栈",
      "score": 10,
      "latitude": 26.91646,
      "longtitude": 100.20531
    },
    {
      "address": "云南省丽江市古城区大研古镇金虹路三公里转盘2号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 140,
      "imgUrl": "",
      "name": "桃园客栈",
      "score": 10,
      "latitude": 26.87909,
      "longtitude": 100.24954
    },
    {
      "address": "七一街八一上段63号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 141,
      "imgUrl": "",
      "name": "天天客栈",
      "score": 10,
      "latitude": 26.86883,
      "longtitude": 100.23875
    },
    {
      "address": "新华街黄山上段40-44号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 142,
      "imgUrl": "",
      "name": "天雨上院客栈",
      "score": 10,
      "latitude": 26.87227,
      "longtitude": 100.23264
    },
    {
      "address": "五一街兴仁巷上段97号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 143,
      "imgUrl": "",
      "name": "童话客栈",
      "score": 10,
      "latitude": 26.87247,
      "longtitude": 100.23671
    },
    {
      "address": "新华街黄山上段60-1",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 144,
      "imgUrl": "",
      "name": "万古客栈",
      "score": 10,
      "latitude": 26.87122,
      "longtitude": 100.23222
    },
    {
      "address": "狮子山公园东90米",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 145,
      "imgUrl": "",
      "name": "万景楼",
      "score": 10,
      "latitude": 26.87118,
      "longtitude": 100.23292
    },
    {
      "address": "束河东康6组37号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 146,
      "imgUrl": "",
      "name": "望星空客栈",
      "score": 10,
      "latitude": 26.91907,
      "longtitude": 100.207
    },
    {
      "address": "束河龙泉路老办事处与指挥部中段",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 147,
      "imgUrl": "",
      "name": "望月居客栈",
      "score": 10,
      "latitude": 26.91862,
      "longtitude": 100.20711
    },
    {
      "address": "街尾村19号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 148,
      "imgUrl": "",
      "name": "文馨小筑客栈",
      "score": 10,
      "latitude": 26.92101,
      "longtitude": 100.20523
    },
    {
      "address": "五一街文林巷73号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 149,
      "imgUrl": "",
      "name": "文渊阁客栈",
      "score": 10,
      "latitude": 26.8762,
      "longtitude": 100.24659
    },
    {
      "address": "八河街3家村东段192号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 150,
      "imgUrl": "",
      "name": "问心客栈",
      "score": 10,
      "latitude": 26.89781,
      "longtitude": 100.18958
    },
    {
      "address": "九鼎街42号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 151,
      "imgUrl": "",
      "name": "蜗牛时光客栈",
      "score": 10,
      "latitude": 26.9182,
      "longtitude": 100.20419
    },
    {
      "address": "束河古镇鼎业街148号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 152,
      "imgUrl": "",
      "name": "溪谷客栈（吉奥古店）",
      "score": 10,
      "latitude": 26.87695,
      "longtitude": 100.23388
    },
    {
      "address": "街尾巷33号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 153,
      "imgUrl": "",
      "name": "溪亭客栈",
      "score": 10,
      "latitude": 26.92039,
      "longtitude": 100.20521
    },
    {
      "address": "街尾村",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 154,
      "imgUrl": "",
      "name": "喜塘客栈",
      "score": 10,
      "latitude": 26.92094,
      "longtitude": 100.20499
    },
    {
      "address": "中和路王家巷70号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 155,
      "imgUrl": "",
      "name": "闲云轻尘客栈",
      "score": 10,
      "latitude": 26.92238,
      "longtitude": 100.20601
    },
    {
      "address": "北门街子云巷11号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 156,
      "imgUrl": "",
      "name": "香雪木舍客栈",
      "score": 10,
      "latitude": 26.87811,
      "longtitude": 100.2387
    },
    {
      "address": "束河古镇中和路4号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 157,
      "imgUrl": "",
      "name": "湘爱客栈（主题餐厅）",
      "score": 10,
      "latitude": 26.92324,
      "longtitude": 100.20621
    },
    {
      "address": "光义街忠义巷60号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 158,
      "imgUrl": "",
      "name": "祥和院客栈",
      "score": 10,
      "latitude": 26.86758,
      "longtitude": 100.23366
    },
    {
      "address": "束河东康8组",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 159,
      "imgUrl": "",
      "name": "向阳居",
      "score": 10,
      "latitude": 26.92155,
      "longtitude": 100.20993
    },
    {
      "address": "狮子山公园北100米",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 160,
      "imgUrl": "",
      "name": "心飞杨客栈",
      "score": 10,
      "latitude": 26.87263,
      "longtitude": 100.22949
    },
    {
      "address": "义尚街文林巷28号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 161,
      "imgUrl": "",
      "name": "心旅客栈",
      "score": 10,
      "latitude": 26.8787,
      "longtitude": 100.2468
    },
    {
      "address": "白龙潭假日酒店南90米（祥和路北）",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 162,
      "imgUrl": "",
      "name": "新光客栈",
      "score": 10,
      "latitude": 26.86267,
      "longtitude": 100.22954
    },
    {
      "address": "束河北门束白路",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 163,
      "imgUrl": "",
      "name": "雪莲花客栈",
      "score": 10,
      "latitude": 26.92626,
      "longtitude": 100.21063
    },
    {
      "address": "文明巷86号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 164,
      "imgUrl": "",
      "name": "烟岚翠舍客栈",
      "score": 10,
      "latitude": 26.87315,
      "longtitude": 100.24419
    },
    {
      "address": "束河红叶巷10号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 165,
      "imgUrl": "",
      "name": "一见如故",
      "score": 10,
      "latitude": 26.92264,
      "longtitude": 100.20333
    },
    {
      "address": "义尚街文林巷14号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 166,
      "imgUrl": "",
      "name": "一棵树客栈",
      "score": 10,
      "latitude": 26.87557,
      "longtitude": 100.24463
    },
    {
      "address": "义尚街文林巷178号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 167,
      "imgUrl": "",
      "name": "伊香阁客栈",
      "score": 10,
      "latitude": 26.87475,
      "longtitude": 100.2436
    },
    {
      "address": "七一街八一上段42号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 168,
      "imgUrl": "",
      "name": "怡心雅居客栈",
      "score": 10,
      "latitude": 26.86945,
      "longtitude": 100.23834
    },
    {
      "address": "义尚街文明巷48",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 169,
      "imgUrl": "",
      "name": "颐和文苑",
      "score": 10,
      "latitude": 26.87372,
      "longtitude": 100.24198
    },
    {
      "address": "五一街文林巷26号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 170,
      "imgUrl": "",
      "name": "苡均悦府客栈",
      "score": 10,
      "latitude": 26.87505,
      "longtitude": 100.24417
    },
    {
      "address": "仁里新一村四组11号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 171,
      "imgUrl": "",
      "name": "忆明轩客栈",
      "score": 10,
      "latitude": 26.92445,
      "longtitude": 100.20836
    },
    {
      "address": "束河北门中和路2号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 172,
      "imgUrl": "",
      "name": "驿花雨客栈",
      "score": 10,
      "latitude": 26.92359,
      "longtitude": 100.2061
    },
    {
      "address": "束河东康小道",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 173,
      "imgUrl": "",
      "name": "逸客国际青年客栈",
      "score": 10,
      "latitude": 26.91785,
      "longtitude": 100.21075
    },
    {
      "address": "束河仁里路17号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 174,
      "imgUrl": "",
      "name": "逸墅客栈",
      "score": 10,
      "latitude": 26.92145,
      "longtitude": 100.20236
    },
    {
      "address": "官方花园别墅第649棟",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 175,
      "imgUrl": "",
      "name": "逸心苑649号客栈",
      "score": 10,
      "latitude": 26.87627,
      "longtitude": 100.23593
    },
    {
      "address": "官方花园别墅第654棟",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 176,
      "imgUrl": "",
      "name": "逸心苑654号客栈",
      "score": 10,
      "latitude": 26.87627,
      "longtitude": 100.23593
    },
    {
      "address": "北门停车场入口对面",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 177,
      "imgUrl": "",
      "name": "逸雅客栈",
      "score": 10,
      "latitude": 26.87627,
      "longtitude": 100.23593
    },
    {
      "address": "七一街八一下段99号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 178,
      "imgUrl": "",
      "name": "吟然阁",
      "score": 10,
      "latitude": 26.86763,
      "longtitude": 100.24241
    },
    {
      "address": "古城义和昭庆村77号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 179,
      "imgUrl": "",
      "name": "樱桃客栈",
      "score": 10,
      "latitude": 26.86463,
      "longtitude": 100.23825
    },
    {
      "address": "七一街兴文巷35号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 180,
      "imgUrl": "",
      "name": "优胜美地",
      "score": 10,
      "latitude": 26.86867,
      "longtitude": 100.23756
    },
    {
      "address": "光义街忠义巷134号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 181,
      "imgUrl": "",
      "name": "悠觅客栈",
      "score": 10,
      "latitude": 26.86833,
      "longtitude": 100.23367
    },
    {
      "address": "古佑巷136号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 182,
      "imgUrl": "",
      "name": "余庆雅舍",
      "score": 10,
      "latitude": 26.86599,
      "longtitude": 100.23986
    },
    {
      "address": "五一街兴仁上段20号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 183,
      "imgUrl": "",
      "name": "语焉阁",
      "score": 10,
      "latitude": 26.87299,
      "longtitude": 100.23702
    },
    {
      "address": "新华街双石段43号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 184,
      "imgUrl": "",
      "name": "玉满楼",
      "score": 10,
      "latitude": 26.875,
      "longtitude": 100.23241
    },
    {
      "address": "七一街崇仁巷95号附近",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 185,
      "imgUrl": "",
      "name": "御鹿二分店客栈",
      "score": 10,
      "latitude": 26.87002,
      "longtitude": 100.23922
    },
    {
      "address": "古城区官院巷19号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 186,
      "imgUrl": "",
      "name": "原乡客栈",
      "score": 10,
      "latitude": 26.86977,
      "longtitude": 100.23507
    },
    {
      "address": "七一街兴文巷91号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 187,
      "imgUrl": "",
      "name": "原乡文苑客栈",
      "score": 10,
      "latitude": 26.86815,
      "longtitude": 100.23796
    },
    {
      "address": "光义街现文巷97号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 188,
      "imgUrl": "",
      "name": "缘之初",
      "score": 10,
      "latitude": 26.87164,
      "longtitude": 100.23427
    },
    {
      "address": "阿妈火腿鸡东60米",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 189,
      "imgUrl": "",
      "name": "缘之旅客栈",
      "score": 10,
      "latitude": 26.86562,
      "longtitude": 100.24465
    },
    {
      "address": "拐柳巷8号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 190,
      "imgUrl": "",
      "name": "玥色客栈",
      "score": 10,
      "latitude": 26.91957,
      "longtitude": 100.20666
    },
    {
      "address": "中和路60号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 191,
      "imgUrl": "",
      "name": "玥色小天地客栈",
      "score": 10,
      "latitude": 26.87284,
      "longtitude": 100.22921
    },
    {
      "address": "狮子山公园北130米",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 192,
      "imgUrl": "",
      "name": "云飞杨客栈",
      "score": 10,
      "latitude": 26.87284,
      "longtitude": 100.22921
    },
    {
      "address": "金茂雪山语留园128-130栋",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 193,
      "imgUrl": "",
      "name": "云庐花园别墅",
      "score": 10,
      "latitude": 26.91228,
      "longtitude": 100.22404
    },
    {
      "address": "金茂雪山语103栋留园1-101,201,301",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 194,
      "imgUrl": "",
      "name": "云庐花园公寓1",
      "score": 10,
      "latitude": 26.91228,
      "longtitude": 100.22404
    },
    {
      "address": "金茂雪山语103栋留园1-102,202,302",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 195,
      "imgUrl": "",
      "name": "云庐花园公寓2",
      "score": 10,
      "latitude": 26.91228,
      "longtitude": 100.22404
    },
    {
      "address": "五一街文治巷108号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 196,
      "imgUrl": "",
      "name": "云上公馆客栈",
      "score": 10,
      "latitude": 26.87236,
      "longtitude": 100.23877
    },
    {
      "address": "束河古镇东康村7组5号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 197,
      "imgUrl": "",
      "name": "云上居（云彼客栈）",
      "score": 10,
      "latitude": 26.92144,
      "longtitude": 100.20833
    },
    {
      "address": "光义街光碧巷27号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 198,
      "imgUrl": "",
      "name": "只为等你（木府店）",
      "score": 10,
      "latitude": 26.86878,
      "longtitude": 100.23185
    },
    {
      "address": "五一街兴仁下段43",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 199,
      "imgUrl": "",
      "name": "只因你（古桥院）",
      "score": 10,
      "latitude": 26.87233,
      "longtitude": 100.23581
    },
    {
      "address": "七一街八一下段95号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 200,
      "imgUrl": "",
      "name": "只因有你客栈",
      "score": 10,
      "latitude": 26.86796,
      "longtitude": 100.24255
    },
    {
      "address": "龙泉路80号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 201,
      "imgUrl": "",
      "name": "芷园雅轩客栈",
      "score": 10,
      "latitude": 26.92126,
      "longtitude": 100.20518
    },
    {
      "address": "南门街依古巷7号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 202,
      "imgUrl": "",
      "name": "卓来阁",
      "score": 10,
      "latitude": 26.86697,
      "longtitude": 100.23889
    },
    {
      "address": "五一街文治巷1号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 203,
      "imgUrl": "",
      "name": "子非鱼客栈",
      "score": 10,
      "latitude": 26.87376,
      "longtitude": 100.2392
    },
    {
      "address": "五一街王家巷10号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 204,
      "imgUrl": "",
      "name": "紫藤北苑客栈",
      "score": 10,
      "latitude": 26.87124,
      "longtitude": 100.24009
    },
    {
      "address": "七一街兴文巷35号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 205,
      "imgUrl": "",
      "name": "紫藤缘客栈",
      "score": 10,
      "latitude": 26.86924,
      "longtitude": 100.23721
    },
    {
      "address": "古城八一街下段９８号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 206,
      "imgUrl": "",
      "name": "自由自在客栈",
      "score": 10,
      "latitude": 26.86769,
      "longtitude": 100.24212
    },
    {
      "address": "电信大楼斜对面",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 27,
      "imgUrl": "/mages/scenery/1-1.png",
      "name": "701假日酒店",
      "score": 8.8,
      "latitude": 26.88292,
      "longtitude": 100.2196
    },
    {
      "address": "康普路拐柳巷1号",
      "category": 3,
      "city": "丽江",
      "commentNumber": 0,
      "id": 28,
      "imgUrl": "/mages/scenery/2-1.png",
      "name": "K2国际青年旅社",
      "score": 8.4,
      "latitude": 26.91898,
      "longtitude": 100.20612
    }
  ];
}

module.exports = {
  get_mapdata: get_mapdata
}